{/* TODO: Legal review by a Spanish DPO / lawyer required before public launch. */}
export function PrivacyEn() {
  return (
    <>
      <p>
        This Privacy Policy explains what personal data Dulce collects, how we use it, and the
        rights you have over it. It applies to both this website (
        <strong>dulceglucosa.com</strong>) and the Dulce mobile application.
      </p>

      <h2 id="controller">1. Data controller</h2>
      <p>
        The data controller is <strong>Giorgio Khimshiashvili</strong>, operating as a sole
        trader, based in Spain. You can contact us about anything related to your data at{" "}
        <a href="mailto:hola@dulceglucosa.com">hola@dulceglucosa.com</a>.
      </p>

      <h2 id="data">2. What data we collect</h2>
      <h3>2.1 Website</h3>
      <ul>
        <li>
          <strong>Waitlist:</strong> your email and your session's language.
        </li>
        <li>
          <strong>Beta form:</strong> name, email, CGM device, and region. Optionally, any
          notes you choose to share.
        </li>
        <li>
          <strong>Minimal technical data:</strong> an anonymous hash (SHA-256) of your IP
          combined with a daily-rotating salt, used only to throttle form abuse. We never
          store the raw IP.
        </li>
        <li>
          <strong>Anonymous analytics:</strong> we use Vercel Analytics, which sets no cookies
          and collects no personal identifiers. It only measures page views and performance.
        </li>
      </ul>

      <h3>2.2 In the app, on your device</h3>
      <ul>
        <li>
          <strong>Your LibreLinkUp credentials.</strong> You sign in with the email and
          password of your LibreLinkUp account (Abbott). They are stored only in your
          device's secure keychain and are used to fetch your glucose from Abbott's service.
          They are never sent to Dulce servers.
        </li>
        <li>
          <strong>Glucose readings</strong> fetched from LibreLinkUp, stored in a local
          database on your device.
        </li>
        <li>
          <strong>Your logbook</strong>: carbohydrates, insulin, manual glucose entries and
          notes. Stored locally.
        </li>
        <li>
          <strong>Apple Health data</strong> in read-only mode, if you grant permission.
        </li>
        <li>
          <strong>Preferences</strong>: units, target range, language, theme, alert settings.
        </li>
      </ul>

      <h3>2.3 The Dulce relay (real-time features)</h3>
      <p>
        Some features need to keep working while your phone is locked or the app is closed:
        the Lock Screen Live Activity, glucose alerts, Apple Watch updates and family
        following. To power them, a small server operated by us (the "relay", hosted on
        Cloudflare) fetches your readings from LibreLinkUp and pushes them to your devices.
        When — and only when — you turn one of these features on, the relay processes:
      </p>
      <ul>
        <li>
          <strong>A LibreLinkUp session token</strong> (not your password), so it can fetch
          readings on your behalf.
        </li>
        <li>
          <strong>Anonymous push tokens</strong> for your devices, issued by Apple or Google.
          They identify a device for notifications; they don't identify you personally.
        </li>
        <li>
          <strong>Your most recent glucose readings</strong>, kept as a short rolling window
          needed to render the Live Activity, watch and follower views. The relay is not a
          long-term store of your health history — that stays on your device.
        </li>
        <li>
          <strong>The minimum settings</strong> needed to format what you see (units, target
          range, alert thresholds, language).
        </li>
      </ul>
      <p>
        If you never enable these features, nothing is sent to Dulce servers. If you turn
        them off, sign out, or delete your account in Settings, the associated relay data is
        deleted.
      </p>

      <h3>2.4 Family following</h3>
      <p>
        If you invite someone to follow you, the relay delivers your recent readings and
        alerts to their device from the moment they accept — earlier history is not shared.
        Short predefined nudge messages between you and your followers also pass through the
        relay. You can revoke a follower's access at any time, and you can turn off follower
        messages entirely.
      </p>

      <h3>2.5 Purchases</h3>
      <p>
        Subscriptions are processed by <strong>Apple</strong>. We never see your name, card
        or billing details. We use <strong>RevenueCat</strong> to validate subscriptions
        using a random identifier generated by the app — not your email or your identity.
      </p>

      <h2 id="purpose">3. Why we use your data</h2>
      <ul>
        <li>Show your glucose on your devices and, if you choose, your followers' devices.</li>
        <li>Deliver the alerts you configure.</li>
        <li>Validate your subscription and unlock Pro features.</li>
        <li>Let you know when Dulce is available (waitlist).</li>
        <li>Protect the site from abuse (IP hash, rate limit).</li>
        <li>Understand which pages perform best (anonymous analytics).</li>
        <li>Comply with legal obligations and respond to your rights requests.</li>
      </ul>

      <h2 id="legal-basis">4. Legal basis</h2>
      <ul>
        <li>
          <strong>Explicit consent</strong> (Art. 9(2)(a) GDPR): processing your glucose data
          through the relay when you enable real-time features or family following.
        </li>
        <li>
          <strong>Contract</strong> (Art. 6(1)(b) GDPR): providing the app and the features
          you subscribe to.
        </li>
        <li>
          <strong>Consent</strong> (Art. 6(1)(a) GDPR): when you join the waitlist or beta.
        </li>
        <li>
          <strong>Legitimate interest</strong> (Art. 6(1)(f) GDPR): basic site security and
          anonymous analytics.
        </li>
      </ul>

      <h2 id="health">5. Special category data (Art. 9 GDPR)</h2>
      <p>
        Glucose readings and other health data are <strong>special categories</strong> of
        personal data. Our approach:
      </p>
      <ul>
        <li>By default, they are processed and stored only on your device.</li>
        <li>
          They reach our relay only when you explicitly enable a feature that requires it,
          and only as a short-lived recent window.
        </li>
        <li>They are always encrypted in transit (TLS).</li>
        <li>
          They are used exclusively to deliver your own data to your own devices and to the
          followers you choose — never for advertising, profiling or resale.
        </li>
      </ul>

      <h2 id="retention">6. How long we keep your data</h2>
      <ul>
        <li>
          <strong>Relay data:</strong> recent readings are overwritten continuously; session
          and push tokens are kept while the feature is active and deleted when you disable
          it, sign out, or delete your account (Settings → Delete account).
        </li>
        <li>
          <strong>App data on your device:</strong> until you delete it or uninstall the app.
        </li>
        <li>
          <strong>Waitlist:</strong> until launch + 6 months, or until you ask to be removed.
        </li>
        <li>
          <strong>Beta form:</strong> for the duration of the beta + 12 months.
        </li>
        <li>
          <strong>IP hash:</strong> 30 days.
        </li>
      </ul>

      <h2 id="recipients">7. Who we share your data with</h2>
      <p>
        We share data only with the providers strictly required to run the service. They all
        act as processors under contract:
      </p>
      <ul>
        <li>
          <strong>Cloudflare</strong> — hosts the Dulce relay described above.
        </li>
        <li>
          <strong>Apple</strong> — push notifications (APNs), Live Activities, Apple Health
          (on-device), and payments.
        </li>
        <li>
          <strong>Google Firebase</strong> — push notifications on Android.
        </li>
        <li>
          <strong>RevenueCat</strong> — subscription validation (pseudonymous ID only).
        </li>
        <li>
          <strong>Supabase</strong> (waitlist and beta storage) — hosted in the EU (eu-west-3).
        </li>
        <li>
          <strong>Resend</strong> (waitlist confirmation email) and <strong>Vercel</strong>{" "}
          (website hosting and anonymous analytics).
        </li>
        <li>
          <strong>Abbott (LibreLinkUp)</strong> — your device and our relay connect to
          Abbott's service with your credentials/session to fetch your readings. That
          connection is governed by Abbott's own privacy policy.
        </li>
      </ul>
      <p>
        We never sell, rent or hand over your data to third parties for advertising or
        commercial purposes.
      </p>

      <h2 id="transfers">8. International transfers</h2>
      <p>
        Some of our processors (Cloudflare, RevenueCat, Resend, Vercel, Apple, Google)
        process data in the US or at global edge locations. Transfers are made under the
        European Commission's Standard Contractual Clauses (SCCs) or equivalent frameworks
        (DPF). You can request a copy of these safeguards at{" "}
        <a href="mailto:hola@dulceglucosa.com">hola@dulceglucosa.com</a>.
      </p>

      <h2 id="rights">9. Your rights</h2>
      <p>As a data subject, you have the right to:</p>
      <ul>
        <li>Access your personal data.</li>
        <li>Rectify it if inaccurate.</li>
        <li>Request its deletion.</li>
        <li>Object to processing or request restriction.</li>
        <li>Portability of data you have provided.</li>
        <li>Withdraw your consent at any time.</li>
      </ul>
      <p>
        The fastest way to delete everything Dulce holds about you is{" "}
        <strong>Settings → Delete account</strong> inside the app. You can also exercise any
        of these rights by writing to{" "}
        <a href="mailto:hola@dulceglucosa.com">hola@dulceglucosa.com</a>. We respond within
        30 days at the latest.
      </p>
      <p>
        If you believe our processing does not comply with the law, you have the right to file
        a complaint with the{" "}
        <a href="https://www.aepd.es" target="_blank" rel="noopener">
          Spanish Data Protection Agency (AEPD)
        </a>
        .
      </p>

      <h2 id="minors">10. Children</h2>
      <p>
        Dulce is not directed at children under the age of 14. A parent or legal guardian may
        use Dulce to follow a minor's glucose under their own responsibility. If you believe a
        minor in your care has provided us with data without your consent, contact us and we
        will delete it.
      </p>

      <h2 id="cookies">11. Cookies</h2>
      <p>
        We only use strictly necessary technical cookies (language preference, CSRF token on
        forms). We do not use tracking or advertising cookies. More in our{" "}
        <a href="/en/legal/cookies">Cookie Policy</a>.
      </p>

      <h2 id="changes">12. Changes to this policy</h2>
      <p>
        If we make material changes, we will notify affected users by email or inside the app
        and publish the updated version with its revision date on this page.
      </p>

      <h2 id="contact">13. Contact</h2>
      <p>
        For any questions about this Privacy Policy or the processing of your data, write to{" "}
        <a href="mailto:hola@dulceglucosa.com">hola@dulceglucosa.com</a>.
      </p>
    </>
  );
}
